export const appCopy = {
  publicFallbackAria: 'Зареждане на публичната страница',
  routeErrorEyebrow: 'Временен проблем',
  routeErrorTitle: 'Не успяхме да заредим страницата',
  routeErrorBody: 'Възникна проблем при зареждането. Можеш да опиташ отново след малко.',
  routeErrorRetry: 'Опитай пак',
  loadingMessage: 'Зареждане...',
};

export const navbarCopy = {
  defaultNavLinks: [
    { to: '/', label: 'Начало' },
    { to: '/category/crime', label: 'Криминални', hot: true },
    { to: '/category/underground', label: 'Подземен свят', hot: true },
    { to: '/category/emergency', label: 'Извънредни' },
    { to: '/category/breaking', label: 'Горещо', hot: true },
    { to: '/category/reportage', label: 'Репортажи' },
    { to: '/category/politics', label: 'Политика' },
    { to: '/category/business', label: 'Бизнес' },
    { to: '/category/society', label: 'Общество' },
    { to: '/tipline', label: 'Сигнали', hot: true },
    { to: '/jobs', label: 'Работа' },
    { to: '/court', label: 'Съд' },
    { to: '/events', label: 'Събития' },
    { to: '/games', label: 'Игри', hot: true },
    { to: '/gallery', label: 'Галерия' },
  ],
  defaultSpotlightLinks: [
    { to: '/category/crime', label: 'Горещо', icon: 'Flame', hot: true, tilt: '-2deg' },
    { to: '/category/underground', label: 'Скандали', icon: 'Megaphone', hot: true, tilt: '1.5deg' },
    { to: '/category/society', label: 'Слухове', icon: 'Bell', hot: false, tilt: '-1deg' },
  ],
  searchPlaceholder: 'Търси в сайта...',
};

export const homeCopy = {
  defaultHeadlineWords: ['Спри', 'и', 'прочети'],
  defaultSpotlightLinks: [
    { to: '/category/crime', label: 'Горещо от редакцията', icon: 'Flame', hot: true, tilt: '-1.3deg' },
    { to: '/category/underground', label: 'Скандали', icon: 'Megaphone', hot: true, tilt: '1deg' },
    { to: '/category/society', label: 'Слухове', icon: 'Bell', hot: false, tilt: '-0.8deg' },
  ],
  loadErrorBadge: 'Проблем',
  loadErrorTitle: 'Съдържанието не се зареди',
  loadErrorRetry: 'Обнови страницата',
  emptyBadge: 'Няма новини',
  emptyTitle: 'Все още няма публикувани материали',
  emptyBody: 'Провери отново след малко за нови публикации.',
  featuredLabel: 'Горещо от редакцията',
  sponsoredLabel: 'Платени публикации',
  crimeLabel: 'Криминално / подземен свят',
  latestLabel: 'Последни новини',
  latestEmptyTitle: 'Още няма подредени акценти',
  latestEmptyBody: 'Обнови страницата, за да заредим най-новите материали.',
  latestEmptyButton: 'Обнови',
  reportageLabel: 'Репортажи',
  breakingLabel: 'Breaking',
  emergencyLabel: 'Извънредни',
  defaultCategoryLabel: 'Новини',
  latestLeadSticker: 'Акцент',
  latestSecondSticker: 'Важно',
  latestThirdSticker: 'Новина',
  latestFourthSticker: 'Гледано',
  latestFifthSticker: 'Тема',
};

export const searchCopy = {
  title: 'Търсене',
  emptyTitle: 'Няма резултати',
  emptyBody: 'Пробвай с по-кратка или по-конкретна заявка.',
  inputPlaceholder: 'Търси статии, работа, съд, събития...',
  clearSearch: 'Изчисти търсенето',
  resultsFor: 'Резултати за',
  loading: 'Търсене...',
  fallbackNotice: 'Показваме локални резултати заради временен проблем.',
  trendingTitle: 'Популярни търсения',
  recentTitle: 'Последни търсения',
  suggestionsTitle: 'Предложения',
  noRecentSearches: 'Все още няма запазени търсения.',
  sections: {
    all: 'Всичко',
    articles: 'Статии',
    jobs: 'Работа',
    court: 'Съд',
    events: 'Събития',
    wanted: 'Издирвани',
  },
};

export const dashboardCopy = {
  loadingAnalytics: 'Зареждане на аналитиката...',
  title: 'Табло',
  subtitle: 'Общ преглед на zNews CMS.',
  exportLabel: 'Експорт',
  resetLabel: 'Нулиране',
  exportError: 'Експортът не успя',
  resetError: 'Нулирането не успя',
  resetConfirm: 'Това ще върне демо данните и ще изтрие текущите промени. Сигурен ли си?',
  noStats: 'Нямаш права за този изглед.',
  rpSection: 'Редакционни секции',
  recentArticles: 'Последни статии',
  manageArticles: 'Към статиите',
  noArticles: 'Все още няма статии.',
  teamTitle: 'Екип',
  teamManage: 'Управление',
  noUsers: 'Няма добавени потребители.',
  stats: {
    articles: 'Статии',
    views: 'Преглеждания',
    comments: 'Коментари',
    gallery: 'Галерия',
    pendingComments: 'чакащи',
    wanted: 'Издирвани',
    jobs: 'Работа',
    court: 'Съд',
    events: 'Събития',
    polls: 'Анкети',
  },
};

export const tipCopy = {
  title: 'Сигнали от читатели',
  subtitle: 'Преглед и обработка на входящите сигнали',
  refresh: 'Обнови',
  searchPlaceholder: 'Търси по текст или локация...',
  emptyState: 'Няма намерени сигнали.',
  deleteConfirm: 'Сигурен ли си, че искаш да изтриеш този сигнал?',
  deleteSuccess: 'Сигналът беше изтрит',
  statusUpdated: 'Статусът е обновен',
  errorPrefix: 'Грешка: ',
  convertToArticle: 'Превърни в статия',
  reject: 'Отхвърли',
  missingText: '(няма текст)',
  newStatus: 'Нов',
  processedStatus: 'Обработен',
  rejectedStatus: 'Отхвърлен',
  prefillTitlePrefix: 'Сигнал: ',
  unknownLocation: 'Неуточнена локация',
};
