export const appCopy = {
  publicFallbackAria: 'Зареждане на публичната страница',
  routeErrorEyebrow: 'Временен проблем',
  routeErrorTitle: 'Не успяхме да заредим страницата',
  routeErrorBody: 'Възникна проблем при зареждането. Можеш да опиташ отново след малко.',
  routeErrorRetry: 'Опитай пак',
  loadingMessage: 'Зареждане...',
};

export const navbarCopy = {
  defaultNavLinks: [
    { to: '/', label: 'Начало' },
    { to: '/category/crime', label: 'Криминални', hot: true },
    { to: '/category/underground', label: 'Подземен свят', hot: true },
    { to: '/category/emergency', label: 'Извънредни' },
    { to: '/category/breaking', label: 'Горещо', hot: true },
    { to: '/category/reportage', label: 'Репортажи' },
    { to: '/category/politics', label: 'Политика' },
    { to: '/category/business', label: 'Бизнес' },
    { to: '/category/society', label: 'Общество' },
    { to: '/tipline', label: 'Сигнали', hot: true },
    { to: '/jobs', label: 'Работа' },
    { to: '/court', label: 'Съд' },
    { to: '/events', label: 'Събития' },
    { to: '/games', label: 'Игри', hot: true },
    { to: '/gallery', label: 'Галерия' },
  ],
  defaultSpotlightLinks: [
    { to: '/games', label: 'Игри', icon: 'Gamepad2', hot: false, tilt: '1.8deg' },
    { to: '/category/breaking', label: 'Горещо', icon: 'Flame', hot: true, tilt: '-2deg' },
    { to: '/category/underground', label: 'Подземен свят', icon: 'Megaphone', hot: true, tilt: '1.5deg' },
    { to: '/category/society', label: 'Общество', icon: 'Bell', hot: false, tilt: '-1deg' },
  ],
  searchPlaceholder: 'Търси в сайта...',
};

export const homeCopy = {
  defaultHeadlineWords: ['Шок', 'и', 'сензация!'],
  defaultSpotlightLinks: [
    { to: '/category/breaking', label: 'Горещо', icon: 'Flame', hot: true, tilt: '-1.3deg' },
    { to: '/category/underground', label: 'Подземен свят', icon: 'Megaphone', hot: true, tilt: '1deg' },
    { to: '/category/society', label: 'Общество', icon: 'Bell', hot: false, tilt: '-0.8deg' },
  ],
  defaultBottomPills: [
    { to: '/category/breaking', label: 'Горещо', icon: 'Flame', hot: true, tilt: '-1.3deg' },
    { to: '/category/underground', label: 'Подземен свят', icon: 'Megaphone', hot: true, tilt: '1deg' },
    { to: '/category/society', label: 'Общество', icon: 'Bell', hot: false, tilt: '-0.8deg' },
  ],
  defaultPillLabel: 'Виж повече',
  loadErrorBadge: 'Грешка',
  loadErrorTitle: 'Проблем при зареждане',
  loadErrorRetry: 'Опитай отново',
  emptyBadge: 'Празно',
  emptyTitle: 'Няма публикации',
  emptyBody: 'Провери отново след малко за нови публикации.',
  featuredLabel: 'Горещо от редакцията',
  sponsoredLabel: 'Платени публикации',
  sponsoredDisclosure: 'Платено съдържание от партньори и рекламодатели.',
  crimeLabel: 'Криминални / подземен свят',
  latestLabel: 'Последни новини',
  latestMoreLabel: 'Още новини',
  latestEmptyTitle: 'Няма още публикации за тази секция',
  latestEmptyBody: 'Провери отново след малко или обнови страницата.',
  latestEmptyButton: 'Обнови',
  sectionViewAllLabel: 'Виж всички',
  reportageLabel: 'Репортажи',
  breakingLabel: 'Извънредни',
  emergencyLabel: 'Полиция',
  defaultCategoryLabel: 'Новини',
  latestLeadSticker: 'Фронт',
  latestSecondSticker: 'Досие',
  latestThirdSticker: 'Радар',
  latestFourthSticker: 'Сигнал',
  latestFifthSticker: 'Ключово',
  quickCategoriesMoreLabel: 'Още теми',
  quickCategoriesLessLabel: 'По-малко теми',
};

export const searchCopy = {
  title: 'Търсене',
  emptyTitle: 'Няма резултати',
  emptyBody: 'Пробвай с по-кратка или по-конкретна заявка.',
  inputPlaceholder: 'Търси по ключова дума...',
  clearSearch: 'Изчисти търсенето',
  resultsFor: 'Резултати за',
  loading: 'Търсене...',
  serviceError: 'Търсенето временно не е достъпно.',
  fallbackNotice: 'Показваме локални резултати заради временен проблем.',
  trendingTitle: 'Популярни търсения',
  recentTitle: 'Последни търсения',
  suggestionsTitle: 'Предложения',
  noRecentSearches: 'Все още няма запазени търсения.',
  wantedRewardLabel: 'Награда',
  sections: {
    all: 'Всичко',
    articles: 'Статии',
    jobs: 'Работа',
    court: 'Съд',
    events: 'Събития',
    wanted: 'Издирвани',
  },
};

export const dashboardCopy = {
  loadingAnalytics: 'Зареждане на аналитичния панел...',
  title: 'Табло',
  subtitle: 'Оперативен преглед на zNews CMS.',
  exportLabel: 'Архив',
  resetLabel: 'Нулирай демо',
  exportError: 'Архивът не можа да бъде създаден.',
  resetError: 'Нулирането не успя.',
  resetConfirm: 'Това ще презапише демонстрационните данни и ще върне системата в начално състояние. Продължаваме ли?',
  noStats: 'Няма видими статистики за текущия профил.',
  rpSection: 'Оперативни секции',
  recentArticles: 'Последни статии',
  manageArticles: 'Към статиите',
  noArticles: 'Няма публикации.',
  teamTitle: 'Екип',
  teamManage: 'Управление',
  noUsers: 'Няма потребители.',
  viewsShort: 'прегл.',
  stats: {
    articles: 'Статии',
    views: 'Преглеждания',
    comments: 'Коментари',
    gallery: 'Галерия',
    pendingComments: 'чакат',
  },
  rpStats: {
    wanted: 'Издирвани',
    jobs: 'Обяви',
    court: 'Дела',
    events: 'Събития',
    polls: 'Анкети',
    classifieds: 'Малки обяви',
    pendingClassifieds: 'нови',
  },
};

export const tipCopy = {
  title: 'Сигнали от читатели',
  subtitle: 'Преглед и обработка на входящите сигнали',
  refresh: 'Обнови',
  searchPlaceholder: 'Търси по текст или локация...',
  emptyState: 'Няма намерени сигнали.',
  deleteConfirm: 'Сигурен ли си, че искаш да изтриеш този сигнал?',
  deleteSuccess: 'Сигналът беше изтрит',
  statusUpdated: 'Статусът е обновен',
  errorPrefix: 'Грешка: ',
  convertToArticle: 'Превърни в статия',
  reject: 'Отхвърли',
  missingText: '(няма текст)',
  newStatus: 'Нов',
  processedStatus: 'Обработен',
  rejectedStatus: 'Отхвърлен',
  prefillTitlePrefix: 'Сигнал: ',
  unknownLocation: 'Неуточнена локация',
};
